// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdpxDCUyhrgHgFw6z972-z5fnowpRhCc',
    appId: '1:601569258432:android:41bc88a007c0eb6a9ef625',
    messagingSenderId: '601569258432',
    projectId: 'pawpal-application-project',
    databaseURL: 'https://pawpal-application-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pawpal-application-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDDEPSlk0CDK013DpV5xjU8RCfNE257Lg',
    appId: '1:601569258432:ios:8911d14f66414eb09ef625',
    messagingSenderId: '601569258432',
    projectId: 'pawpal-application-project',
    databaseURL: 'https://pawpal-application-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pawpal-application-project.firebasestorage.app',
    iosBundleId: 'com.example.pawpalApplication',
  );
}
